#from Add_entry_page import Add_Entry_Page
from AddressBook_gui import AddressBook:
    from AddressBook_gui import main
#from Demo import FileListingCellDataExample:
#from Demo import main
#from Entry import Entry
from database import DataBase
#from firstEx import calculate
#from mywidgets import AddressBook
#from mywidgets import main
